# Makefile to build

help:
	@echo "Supported Targets List"
	@echo "	build  - Thaki FTP server"
	@echo "	debug  - Debug Thaki FTP server"
	@echo "	clean  - clean all build files"

build: thakifd

debug: thakifd
	OPTIONS="-g -Wall"

clean:
	echo "Cleaning.."